const projectsData = [
  {
    id: 1,
    title: "Fresh Italian Restaurant",
    label: "Go to Fresh Italian Restaurant Website",
    description:
      "Restaurant website with table reservation module. Scroll animations made with Intersection Observer API.",
    imageUrl: "../images/restaurant.jpg",
    link: "#",
    githubLink: "#",
    figmaLink: "#",
    tools: [
      "html5",
      "css3",
      "sass",
      "javascript",
      "react",
      "react hooks",
      "context API",
      "nodejs",
      "express",
    ],
  },
  {
    id: 2,
    title: "Christmas Cards Generator",
    label: "Go to Christmas Cards Generator",
    description:
      "Card generator with 25 palettes and 10 font pairs to choose from. Images are provided by Unsplash API. Card download and custom image upload features.",
    imageUrl: "../images/card-generator.jpg",
    link: "#",
    githubLink: "#",
    figmaLink: "#",
    tools: [
      "html5",
      "css3",
      "sass",
      "javascript",
      "react",
      "react hooks",
      "context API",
      "typescript",
      "unsplash API",
    ],
  },
  {
    id: 3,
    title: "Music Scales Learning App",
    label: "Go to Music Scales Learning App",
    description:
      "App displays notes, chords with keyboard and guitar sounds of selected music scale.",
    imageUrl: "../images/scales.jpg",
    link: "#",
    githubLink: "#",
    tools: ["html5", "css3", "sass", "javascript"],
  },
  {
    id: 4,
    title: "Quotes App",
    label: "Go to Quotes App",
    description:
      "App displays random quote from database, with search quote by author and add quote features.",
    imageUrl: "../images/quotes.jpg",
    link: "#",
    githubLink: "#",
    figmaLink: "#",
    tools: [
      "html5",
      "css3",
      "sass",
      "javascript",
      "nodejs",
      "express",
      "mongoDB",
      "webpack",
    ],
  },
];

export default projectsData;